export const pokemonDescription = [
  { name: 'Bulbasaur', id: 1, description: 'Grass-type with a bulb on its back that blooms over time' },
  { name: 'Ivysaur', id: 2, description: 'Grass/poison-type with a pink flower budding from its back' },
  { name: 'Venusaur', id: 3, description: 'Large toad-like creature with a fully bloomed flower' },
  { name: 'Charmander', id: 4, description: 'Fire-type lizard with a flame on its tail' },
  { name: 'Charmeleon', id: 5, description: 'Red dragon-like creature with horns and flame' },
  { name: 'Charizard', id: 6, description: 'Orange dragon with blue wings that spits fire' },
  { name: 'Squirtle', id: 7, description: 'Blue turtle with a brown shell for defense' },
  { name: 'Wartortle', id: 8, description: 'Blue creature with fuzzy ears and protective shell' },
  { name: 'Blastoise', id: 9, description: 'Armored water turtle with cannons on shell' },
  { name: 'Caterpie', id: 10, description: 'Green caterpillar with yellow antenna' },
  { name: 'Metapod', id: 11, description: 'Cocoon-like creature with hardened exterior' },
  { name: 'Butterfree', id: 12, description: 'Purple butterfly with large transparent wings' },
  { name: 'Weedle', id: 13, description: 'Venomous caterpillar with spikes and stinger' },
  { name: 'Kakuna', id: 14, description: 'Yellow cocoon enclosed in hardened shell' },
  { name: 'Beedrill', id: 15, description: 'Large wasp with sharp stingers' },
  { name: 'Pidgey', id: 16, description: 'Small brown bird with red feet' },
  { name: 'Pidgeotto', id: 17, description: 'Larger pigeon with skilled flight' },
  { name: 'Pidgeot', id: 18, description: 'Powerful flying bird with massive wings' },
  { name: 'Rattata', id: 19, description: 'Purple mouse with sharp teeth' },
  { name: 'Raticate', id: 20, description: 'Larger rodent with buck teeth' },
  { name: 'Spearow', id: 21, description: 'Small orange bird with pointed beak' },
  { name: 'Fearow', id: 22, description: 'Large brown bird with long neck' },
  { name: 'Ekans', id: 23, description: 'Purple snake that expands when threatened' },
  { name: 'Arbok', id: 24, description: 'Massive cobra with intimidating hood pattern' },
  { name: 'Pikachu', id: 25, description: 'Yellow mouse with red cheeks emitting electricity' },
  { name: 'Raichu', id: 26, description: 'Larger yellow rodent with orange striped tail' },
  { name: 'Sandshrew', id: 27, description: 'Yellow armadillo that digs underground' },
  { name: 'Sandslash', id: 28, description: 'Spiky sand creature with sharp claws' },
  { name: 'Nidoran♀', id: 29, description: 'Small purple female with poisonous spikes' },
  { name: 'Nidorina', id: 30, description: 'Purple creature with horn and venom' },
  { name: 'Nidoqueen', id: 31, description: 'Powerful female with poisonous spikes' },
  { name: 'Nidoran♂', id: 32, description: 'Small purple male with sharp horn' },
  { name: 'Nidorino', id: 33, description: 'Purple male with developing horn' },
  { name: 'Nidoking', id: 34, description: 'Powerful male with large horn' },
  { name: 'Clefairy', id: 35, description: 'Pink fairy-like creature with pointed ears' },
  { name: 'Clefable', id: 36, description: 'Large pink creature with fairy wings' },
  { name: 'Vulpix', id: 37, description: 'Orange fox with six tails' },
  { name: 'Ninetales', id: 38, description: 'Elegant fox with nine beautiful tails' },
  { name: 'Jigglypuff', id: 39, description: 'Pink round creature whose song puts foes asleep' },
  { name: 'Wigglytuff', id: 40, description: 'Large pink fluffy creature with pointed ears' },
  { name: 'Zubat', id: 41, description: 'Purple bat hanging upside down in caves' },
  { name: 'Golbat', id: 42, description: 'Larger purple bat with sharp fangs' },
  { name: 'Oddish', id: 43, description: 'Blue creature with grass leaves on head' },
  { name: 'Gloom', id: 44, description: 'Blue plant creature with pink flower' },
  { name: 'Vileplume', id: 45, description: 'Large red flower with leafy base' },
  { name: 'Paras', id: 46, description: 'Orange crab with mushrooms on back' },
  { name: 'Parasect', id: 47, description: 'Large crab dominated by giant mushroom' },
  { name: 'Venonat', id: 48, description: 'Bug creature with large insect-like eyes' },
  { name: 'Venomoth', id: 49, description: 'Purple moth with toxic spores' },
  { name: 'Diglett', id: 50, description: 'Ground creature peeking above soil' },
  { name: 'Dugtrio', id: 51, description: 'Three Diglett heads connected underground' },
  { name: 'Meowth', id: 52, description: 'Gray cat with gold coin on forehead' },
  { name: 'Persian', id: 53, description: 'Elegant cat with sleek fur' },
  { name: 'Psyduck', id: 54, description: 'Yellow duck with psychic powers' },
  { name: 'Golduck', id: 55, description: 'Blue duck with psychic abilities' },
  { name: 'Mankey', id: 56, description: 'Pig-like creature prone to tantrums' },
  { name: 'Primeape', id: 57, description: 'Powerful ape constantly enraged' },
  { name: 'Growlithe', id: 58, description: 'Orange dog loyal with fire-breathing' },
  { name: 'Arcanine', id: 59, description: 'Majestic tiger-like beast with fiery mane' },
  { name: 'Poliwag', id: 60, description: 'Blue tadpole with swirl pattern on belly' },
  { name: 'Poliwhirl', id: 61, description: 'Amphibian with spiral pattern' },
  { name: 'Poliwrath', id: 62, description: 'Powerful humanoid with martial arts' },
  { name: 'Abra', id: 63, description: 'Psychic creature that teleports instantly' },
  { name: 'Kadabra', id: 64, description: 'Powerful psychic with spoon-bending' },
  { name: 'Alakazam', id: 65, description: 'Ultra-intelligent psychic with IQ of 5000' },
  { name: 'Machop', id: 66, description: 'Fighting creature with powerful muscles' },
  { name: 'Machoke', id: 67, description: 'Muscular fighter with enhanced strength' },
  { name: 'Machamp', id: 68, description: 'Four-armed powerhouse with fighting prowess' },
  { name: 'Bellsprout', id: 69, description: 'Plant creature resembling bell' },
  { name: 'Weepinbell', id: 70, description: 'Carnivorous plant that snaps at prey' },
  { name: 'Victreebel', id: 71, description: 'Venus flytrap-like creature with acid' },
  { name: 'Tentacool', id: 72, description: 'Jellyfish with blue body and tentacles' },
  { name: 'Tentacruel', id: 73, description: 'Giant jellyfish with eighty tentacles' },
  { name: 'Slowpoke', id: 74, description: 'Pink psychic creature with slow movement' },
  { name: 'Slowbro', id: 75, description: 'Pink creature with shell on tail' },
  { name: 'Seel', id: 76, description: 'White seal with round body' },
  { name: 'Dewgong', id: 77, description: 'Elegant seal-like creature with ice powers' },
  { name: 'Shellder', id: 78, description: 'Purple clam with hard shell' },
  { name: 'Cloyster', id: 79, description: 'Armored shellfish with sharp spikes' },
  { name: 'Gastly', id: 80, description: 'Purple gas ghost hiding in darkness' },
  { name: 'Haunter', id: 81, description: 'Ghost creature causing cold temperatures' },
  { name: 'Gengar', id: 82, description: 'Shadow ghost hiding in walls' },
  { name: 'Onix', id: 83, description: 'Rock serpent made of connected boulders' },
  { name: 'Drowzee', id: 84, description: 'Tapir-like creature feeding on dreams' },
  { name: 'Hypno', id: 85, description: 'Hypnotic creature with pendulum' },
  { name: 'Krabby', id: 86, description: 'Red crab with powerful claws' },
  { name: 'Kingler', id: 87, description: 'Giant crab with massive claw strength' },
  { name: 'Voltorb', id: 88, description: 'Electric sphere resembling pokéball' },
  { name: 'Electrode', id: 89, description: 'Electric ball rolling at incredible speeds' },
  { name: 'Exeggcute', id: 90, description: 'Six plant creatures in coconut shells' },
  { name: 'Exeggutor', id: 91, description: 'Triple-headed palm tree with psychic powers' },
  { name: 'Cubone', id: 92, description: 'Ground creature wearing bone helmet' },
  { name: 'Marowak', id: 93, description: 'Bone-wielding creature skilled in combat' },
  { name: 'Hitmonlee', id: 94, description: 'Fighting master with spring-like legs' },
  { name: 'Hitmonchan', id: 95, description: 'Boxer with incredible punch velocity' },
  { name: 'Lickitung', id: 96, description: 'Pink creature with extremely long tongue' },
  { name: 'Koffing', id: 97, description: 'Purple gas ball producing toxic fumes' },
  { name: 'Weezing', id: 98, description: 'Dual poison gas spheres connected' },
  { name: 'Rhyhorn', id: 99, description: 'Gray rhino-like creature with spiked armor' },
  { name: 'Rhydon', id: 100, description: 'Armored behemoth with drill-like horn' },
  { name: 'Chansey', id: 101, description: 'Pink nurse-like creature that heals' },
  { name: 'Kangaskhan', id: 102, description: 'Mother creature with pouch for joey' },
  { name: 'Horsea', id: 103, description: 'Small seahorse shooting water spirals' },
  { name: 'Seadra', id: 104, description: 'Sea dragon with spiky fins' },
  { name: 'Goldeen', id: 105, description: 'Red and white goldfish with crown' },
  { name: 'Seaking', id: 106, description: 'Noble fish with sharp horn' },
  { name: 'Staryu', id: 107, description: 'Starfish with glowing red core' },
  { name: 'Starmie', id: 108, description: 'Crystalline starfish with geometric perfection' },
  { name: 'Mr. Mime', id: 109, description: 'Psychic mime creating invisible barriers' },
  { name: 'Jynx', id: 110, description: 'Ice-psychic humanoid with kiss attacks' },
  { name: 'Electabuzz', id: 111, description: 'Electric creature with tiger stripes' },
  { name: 'Magnemite', id: 112, description: 'Electric steel creature with magnetism' },
  { name: 'Magneton', id: 113, description: 'Three Magnemite linked together' },
  { name: 'Farfetch\'d', id: 114, description: 'Duck carrying green onion stick' },
  { name: 'Doduo', id: 115, description: 'Two-headed bird running at speed' },
  { name: 'Dodrio', id: 116, description: 'Three-headed bird with coordination' },
  { name: 'Seel', id: 117, description: 'White seal swimming in frozen waters' },
  { name: 'Dewgong', id: 118, description: 'Sea lion with ice armor' },
  { name: 'Grimer', id: 119, description: 'Purple sludge creature with fumes' },
  { name: 'Muk', id: 120, description: 'Massive sludge pile corroding everything' },
  { name: 'Shellder', id: 121, description: 'Purple clam defending with shell' },
  { name: 'Cloyster', id: 122, description: 'Shellfish with impenetrable spikes' },
  { name: 'Gastly', id: 123, description: 'Ghost hiding in shadows' },
  { name: 'Haunter', id: 124, description: 'Ghost lowering temperatures' },
  { name: 'Gengar', id: 125, description: 'Shadow in walls' },
  { name: 'Onix', id: 126, description: 'Boulder serpent' },
  { name: 'Drowzee', id: 127, description: 'Dream eater' },
  { name: 'Hypno', id: 128, description: 'Psychic hypnotist' },
  { name: 'Krabby', id: 129, description: 'Clawed crustacean' },
  { name: 'Kingler', id: 130, description: 'Powerful crab' },
  { name: 'Voltorb', id: 131, description: 'Electric orb' },
  { name: 'Electrode', id: 132, description: 'Swift electric ball' },
  { name: 'Exeggcute', id: 133, description: 'Coconut cluster' },
  { name: 'Exeggutor', id: 134, description: 'Palm tree heads' },
  { name: 'Cubone', id: 135, description: 'Bone helmet wearer' },
  { name: 'Marowak', id: 136, description: 'Combat bone wielder' },
  { name: 'Hitmonlee', id: 137, description: 'Kicking fighter' },
  { name: 'Hitmonchan', id: 138, description: 'Punching boxer' },
  { name: 'Lickitung', id: 139, description: 'Tongue creature' },
  { name: 'Koffing', id: 140, description: 'Gas ball' },
  { name: 'Weezing', id: 141, description: 'Floating toxins' },
  { name: 'Rhyhorn', id: 142, description: 'Armored rhino' },
  { name: 'Rhydon', id: 143, description: 'Powerful horn beast' },
  { name: 'Chansey', id: 144, description: 'Healing creature' },
  { name: 'Kangaskhan', id: 145, description: 'Mother and joey' },
  { name: 'Horsea', id: 146, description: 'Small seahorse' },
  { name: 'Seadra', id: 147, description: 'Dragon of the sea' },
  { name: 'Goldeen', id: 148, description: 'Royal fish' },
  { name: 'Seaking', id: 149, description: 'Crowned warrior' },
  { name: 'Staryu', id: 150, description: 'Star creature' },
  { name: 'Starmie', id: 151, description: 'Mystical starfish' },
];
