const firstGenPokemonList = [
  { name: 'Bulbasaur', number: 1, description: 'Grass-type with a bulb on its back', gender: 'Male & Female', category: 'Seed' },
  { name: 'Ivysaur', number: 2, description: 'Grass/poison-type with a pink flower budding', gender: 'Male & Female', category: 'Seed' },
  { name: 'Venusaur', number: 3, description: 'Large toad-like creature with fully bloomed flower', gender: 'Male & Female', category: 'Seed' },
  { name: 'Charmander', number: 4, description: 'Fire-type lizard with flame on tail', gender: 'Male & Female', category: 'Lizard' },
  { name: 'Charmeleon', number: 5, description: 'Red dragon-like creature with horns', gender: 'Male & Female', category: 'Flame' },
  { name: 'Charizard', number: 6, description: 'Orange dragon with blue wings', gender: 'Male & Female', category: 'Flame' },
  { name: 'Squirtle', number: 7, description: 'Blue turtle with brown shell', gender: 'Male & Female', category: 'Tiny Turtle' },
  { name: 'Wartortle', number: 8, description: 'Blue creature with fuzzy ears', gender: 'Male & Female', category: 'Turtle' },
  { name: 'Blastoise', number: 9, description: 'Armored water turtle with cannons', gender: 'Male & Female', category: 'Shellfish' },
  { name: 'Caterpie', number: 10, description: 'Green caterpillar with yellow antenna', gender: 'Male & Female', category: 'Worm' },
  { name: 'Metapod', number: 11, description: 'Cocoon-like creature with hardened exterior', gender: 'Male & Female', category: 'Cocoon' },
  { name: 'Butterfree', number: 12, description: 'Purple butterfly with large wings', gender: 'Male & Female', category: 'Butterfly' },
  { name: 'Weedle', number: 13, description: 'Venomous caterpillar with spikes', gender: 'Male & Female', category: 'Hairy Bug' },
  { name: 'Kakuna', number: 14, description: 'Yellow cocoon in hardened shell', gender: 'Male & Female', category: 'Cocoon' },
  { name: 'Beedrill', number: 15, description: 'Large wasp with sharp stingers', gender: 'Male & Female', category: 'Poison Bee' },
  { name: 'Pidgey', number: 16, description: 'Small brown bird with red feet', gender: 'Male & Female', category: 'Tiny Bird' },
  { name: 'Pidgeotto', number: 17, description: 'Larger pigeon with skilled flight', gender: 'Male & Female', category: 'Bird' },
  { name: 'Pidgeot', number: 18, description: 'Powerful flying bird with massive wings', gender: 'Male & Female', category: 'Bird' },
  { name: 'Rattata', number: 19, description: 'Purple mouse with sharp teeth', gender: 'Male & Female', category: 'Mouse' },
  { name: 'Raticate', number: 20, description: 'Larger rodent with buck teeth', gender: 'Male & Female', category: 'Mouse' },
  { name: 'Spearow', number: 21, description: 'Small orange bird with pointed beak', gender: 'Male & Female', category: 'Tiny Bird' },
  { name: 'Fearow', number: 22, description: 'Large brown bird with long neck', gender: 'Male & Female', category: 'Beak' },
  { name: 'Ekans', number: 23, description: 'Purple snake that expands when threatened', gender: 'Male & Female', category: 'Snake' },
  { name: 'Arbok', number: 24, description: 'Massive cobra with intimidating hood', gender: 'Male & Female', category: 'Cobra' },
  { name: 'Pikachu', number: 25, description: 'Yellow mouse with red cheeks emitting electricity', gender: 'Male & Female', category: 'Mouse' },
  { name: 'Raichu', number: 26, description: 'Larger yellow rodent with orange striped tail', gender: 'Male & Female', category: 'Mouse' },
  { name: 'Sandshrew', number: 27, description: 'Yellow armadillo that digs underground', gender: 'Male & Female', category: 'Mouse' },
  { name: 'Sandslash', number: 28, description: 'Spiky sand creature with sharp claws', gender: 'Male & Female', category: 'Mouse' },
  { name: 'Nidoran-f', number: 29, description: 'Small purple female with poisonous spikes', gender: 'Female', category: 'Poison Pin' },
  { name: 'Nidorina', number: 30, description: 'Purple creature with horn and venom', gender: 'Female', category: 'Poison Pin' },
  { name: 'Nidoqueen', number: 31, description: 'Powerful female with poisonous spikes', gender: 'Female', category: 'Drill' },
  { name: 'Nidoran-m', number: 32, description: 'Small purple male with sharp horn', gender: 'Male', category: 'Poison Pin' },
  { name: 'Nidorino', number: 33, description: 'Purple male with developing horn', gender: 'Male', category: 'Poison Pin' },
  { name: 'Nidoking', number: 34, description: 'Powerful male with large horn', gender: 'Male', category: 'Drill' },
  { name: 'Clefairy', number: 35, description: 'Pink fairy-like creature with pointed ears', gender: 'Male & Female', category: 'Fairy' },
  { name: 'Clefable', number: 36, description: 'Large pink creature with fairy wings', gender: 'Male & Female', category: 'Fairy' },
  { name: 'Vulpix', number: 37, description: 'Orange fox with six tails', gender: 'Male & Female', category: 'Fox' },
  { name: 'Ninetales', number: 38, description: 'Elegant fox with nine beautiful tails', gender: 'Male & Female', category: 'Fox' },
  { name: 'Jigglypuff', number: 39, description: 'Pink round creature whose song puts foes asleep', gender: 'Male & Female', category: 'Balloon' },
  { name: 'Wigglytuff', number: 40, description: 'Large pink fluffy creature with pointed ears', gender: 'Male & Female', category: 'Balloon' },
  { name: 'Zubat', number: 41, description: 'Purple bat hanging upside down in caves', gender: 'Male & Female', category: 'Bat' },
  { name: 'Golbat', number: 42, description: 'Larger purple bat with sharp fangs', gender: 'Male & Female', category: 'Bat' },
  { name: 'Oddish', number: 43, description: 'Blue creature with grass leaves on head', gender: 'Male & Female', category: 'Weed' },
  { name: 'Gloom', number: 44, description: 'Blue plant creature with pink flower', gender: 'Male & Female', category: 'Weed' },
  { name: 'Vileplume', number: 45, description: 'Large red flower with leafy base', gender: 'Male & Female', category: 'Flower' },
  { name: 'Paras', number: 46, description: 'Orange crab with mushrooms on back', gender: 'Male & Female', category: 'Mushroom' },
  { name: 'Parasect', number: 47, description: 'Large crab dominated by giant mushroom', gender: 'Male & Female', category: 'Mushroom' },
  { name: 'Venonat', number: 48, description: 'Bug creature with large insect-like eyes', gender: 'Male & Female', category: 'Insect' },
  { name: 'Venomoth', number: 49, description: 'Purple moth with toxic spores', gender: 'Male & Female', category: 'Poison Moth' },
  { name: 'Diglett', number: 50, description: 'Ground creature peeking above soil', gender: 'Male & Female', category: 'Mole' },
  { name: 'Dugtrio', number: 51, description: 'Three Diglett heads connected underground', gender: 'Male & Female', category: 'Mole' },
  { name: 'Meowth', number: 52, description: 'Gray cat with gold coin on forehead', gender: 'Male & Female', category: 'Scratch Cat' },
  { name: 'Persian', number: 53, description: 'Elegant cat with sleek fur', gender: 'Male & Female', category: 'Classy Cat' },
  { name: 'Psyduck', number: 54, description: 'Yellow duck with psychic powers', gender: 'Male & Female', category: 'Duck' },
  { name: 'Golduck', number: 55, description: 'Blue duck with psychic abilities', gender: 'Male & Female', category: 'Duck' },
  { name: 'Mankey', number: 56, description: 'Pig-like creature prone to tantrums', gender: 'Male & Female', category: 'Pig Monkey' },
  { name: 'Primeape', number: 57, description: 'Powerful ape constantly enraged', gender: 'Male & Female', category: 'Pig Monkey' },
  { name: 'Growlithe', number: 58, description: 'Orange dog loyal with fire-breathing', gender: 'Male & Female', category: 'Puppy' },
  { name: 'Arcanine', number: 59, description: 'Majestic tiger-like beast with fiery mane', gender: 'Male & Female', category: 'Legendary' },
  { name: 'Poliwag', number: 60, description: 'Blue tadpole with swirl pattern on belly', gender: 'Male & Female', category: 'Tadpole' },
  { name: 'Poliwhirl', number: 61, description: 'Amphibian with spiral pattern', gender: 'Male & Female', category: 'Tadpole' },
  { name: 'Poliwrath', number: 62, description: 'Powerful humanoid with martial arts', gender: 'Male & Female', category: 'Tadpole' },
  { name: 'Abra', number: 63, description: 'Psychic creature that teleports instantly', gender: 'Male & Female', category: 'Psi' },
  { name: 'Kadabra', number: 64, description: 'Powerful psychic with spoon-bending', gender: 'Male & Female', category: 'Psi' },
  { name: 'Alakazam', number: 65, description: 'Ultra-intelligent psychic with IQ of 5000', gender: 'Male & Female', category: 'Psi' },
  { name: 'Machop', number: 66, description: 'Fighting creature with powerful muscles', gender: 'Male & Female', category: 'Superpower' },
  { name: 'Machoke', number: 67, description: 'Muscular fighter with enhanced strength', gender: 'Male & Female', category: 'Superpower' },
  { name: 'Machamp', number: 68, description: 'Four-armed powerhouse with fighting prowess', gender: 'Male & Female', category: 'Superpower' },
  { name: 'Bellsprout', number: 69, description: 'Plant creature resembling bell', gender: 'Male & Female', category: 'Flower' },
  { name: 'Weepinbell', number: 70, description: 'Carnivorous plant that snaps at prey', gender: 'Male & Female', category: 'Flycatcher' },
  { name: 'Victreebel', number: 71, description: 'Venus flytrap-like creature with acid', gender: 'Male & Female', category: 'Flycatcher' },
  { name: 'Tentacool', number: 72, description: 'Jellyfish with blue body and tentacles', gender: 'Male & Female', category: 'Jellyfish' },
  { name: 'Tentacruel', number: 73, description: 'Giant jellyfish with eighty tentacles', gender: 'Male & Female', category: 'Jellyfish' },
  { name: 'Geodude', number: 74, description: 'Rock creature with floating boulders', gender: 'Male & Female', category: 'Rock' },
  { name: 'Graveler', number: 75, description: 'Larger rocky creature with rolling form', gender: 'Male & Female', category: 'Rock' },
  { name: 'Golem', number: 76, description: 'Massive rock creature with powerful shell', gender: 'Male & Female', category: 'Megaton' },
  { name: 'Ponyta', number: 77, description: 'Yellow horse with flaming mane', gender: 'Male & Female', category: 'Fire Horse' },
  { name: 'Rapidash', number: 78, description: 'Horse with fiery horn and speed', gender: 'Male & Female', category: 'Fire Horse' },
  { name: 'Slowpoke', number: 79, description: 'Pink psychic creature with slow movement', gender: 'Male & Female', category: 'Dopey' },
  { name: 'Slowbro', number: 80, description: 'Pink creature with shell on tail', gender: 'Male & Female', category: 'Hermit Crab' },
  { name: 'Magnemite', number: 81, description: 'Electric steel creature with magnetism', gender: "Unknown", category: 'Magnet' },
  { name: 'Magneton', number: 82, description: 'Three Magnemite linked together', gender: "Unknown", category: 'Magnet' },
  { name: "Farfetch'd", number: 83, description: 'Duck carrying green onion stick', gender: 'Male & Female', category: 'Wild Duck' },
  { name: 'Doduo', number: 84, description: 'Two-headed bird running at speed', gender: 'Male & Female', category: 'Twin Bird' },
  { name: 'Dodrio', number: 85, description: 'Three-headed bird with coordination', gender: 'Male & Female', category: 'Triple Bird' },
  { name: 'Seel', number: 86, description: 'White seal swimming in frozen waters', gender: 'Male & Female', category: 'Sea Lion' },
  { name: 'Dewgong', number: 87, description: 'Sea lion with ice armor', gender: 'Male & Female', category: 'Sea Lion' },
  { name: 'Grimer', number: 88, description: 'Purple sludge creature with fumes', gender: 'Male & Female', category: 'Sludge' },
  { name: 'Muk', number: 89, description: 'Massive sludge pile corroding everything', gender: 'Male & Female', category: 'Sludge' },
  { name: 'Shellder', number: 90, description: 'Purple clam defending with shell', gender: 'Male & Female', category: 'Bivalve' },
  { name: 'Cloyster', number: 91, description: 'Shellfish with impenetrable spikes', gender: 'Male & Female', category: 'Bivalve' },
  { name: 'Gastly', number: 92, description: 'Purple gas ghost hiding in shadows', gender: 'Male & Female', category: 'Gas' },
  { name: 'Haunter', number: 93, description: 'Ghost lowering temperatures around it', gender: 'Male & Female', category: 'Gas' },
  { name: 'Gengar', number: 94, description: 'Shadow ghost hiding in walls', gender: 'Male & Female', category: 'Shadow' },
  { name: 'Onix', number: 95, description: 'Rock serpent made of connected boulders', gender: 'Male & Female', category: 'Rock Snake' },
  { name: 'Drowzee', number: 96, description: 'Tapir-like creature feeding on dreams', gender: 'Male & Female', category: 'Hypnosis' },
  { name: 'Hypno', number: 97, description: 'Hypnotic creature with pendulum', gender: 'Male & Female', category: 'Hypnosis' },
  { name: 'Krabby', number: 98, description: 'Red crab with powerful claws', gender: 'Male & Female', category: 'River Crab' },
  { name: 'Kingler', number: 99, description: 'Giant crab with massive claw strength', gender: 'Male & Female', category: 'Pincer' },
  { name: 'Voltorb', number: 100, description: 'Electric sphere resembling pokéball', gender: "Unknown", category: 'Ball' },
  { name: 'Electrode', number: 101, description: 'Electric ball rolling at incredible speeds', gender: "Unknown", category: 'Ball' },
  { name: 'Exeggcute', number: 102, description: 'Six plant creatures in coconut shells', gender: 'Male & Female', category: 'Egg' },
  { name: 'Exeggutor', number: 103, description: 'Triple-headed palm tree with psychic powers', gender: 'Male & Female', category: 'Coconut' },
  { name: 'Cubone', number: 104, description: 'Ground creature wearing bone helmet', gender: 'Male & Female', category: 'Lonely' },
  { name: 'Marowak', number: 105, description: 'Bone-wielding creature skilled in combat', gender: 'Male & Female', category: 'Bone Keeper' },
  { name: 'Hitmonlee', number: 106, description: 'Fighting master with spring-like legs', gender: 'Male', category: 'Kicking' },
  { name: 'Hitmonchan', number: 107, description: 'Boxer with incredible punch velocity', gender: 'Male', category: 'Punching' },
  { name: 'Lickitung', number: 108, description: 'Pink creature with extremely long tongue', gender: 'Male & Female', category: 'Licking' },
  { name: 'Koffing', number: 109, description: 'Purple gas ball producing toxic fumes', gender: 'Male & Female', category: 'Poison Gas' },
  { name: 'Weezing', number: 110, description: 'Dual poison gas spheres connected', gender: 'Male & Female', category: 'Poison Gas' },
  { name: 'Rhyhorn', number: 111, description: 'Gray rhino-like creature with spiked armor', gender: 'Male & Female', category: 'Spikes' },
  { name: 'Rhydon', number: 112, description: 'Armored behemoth with drill-like horn', gender: 'Male & Female', category: 'Drill' },
  { name: 'Chansey', number: 113, description: 'Pink nurse-like creature that heals', gender: 'Female', category: 'Egg' },
  { name: 'Tangela', number: 114, description: 'Vine-covered creature moving with tentacles', gender: 'Male & Female', category: 'Vine' },
  { name: 'Kangaskhan', number: 115, description: 'Mother creature with pouch for joey', gender: 'Female', category: 'Parent' },
  { name: 'Horsea', number: 116, description: 'Small seahorse shooting water spirals', gender: 'Male & Female', category: 'Dragon' },
  { name: 'Seadra', number: 117, description: 'Sea dragon with spiky fins', gender: 'Male & Female', category: 'Dragon' },
  { name: 'Goldeen', number: 118, description: 'Red and white goldfish with crown', gender: 'Male & Female', category: 'Goldfish' },
  { name: 'Seaking', number: 119, description: 'Noble fish with sharp horn', gender: 'Male & Female', category: 'Goldfish' },
  { name: 'Staryu', number: 120, description: 'Starfish with glowing red core', gender: "Unknown", category: 'Star Shape' },
  { name: 'Starmie', number: 121, description: 'Crystalline starfish with geometric perfection', gender: "Unknown", category: 'Mysterious' },
  { name: 'Mr. Mime', number: 122, description: 'Psychic mime creating invisible barriers', gender: 'Male & Female', category: 'Barrier' },
  { name: 'Scyther', number: 123, description: 'Bug creature with sharp scythe claws', gender: 'Male & Female', category: 'Mantis' },
  { name: 'Jynx', number: 124, description: 'Ice-psychic humanoid with kiss attacks', gender: 'Female', category: 'Human Shape' },
  { name: 'Electabuzz', number: 125, description: 'Electric creature with tiger stripes', gender: 'Male & Female', category: 'Electric' },
  { name: 'Magmar', number: 126, description: 'Fire creature igniting surroundings', gender: 'Male & Female', category: 'Spitfire' },
  { name: 'Pinsir', number: 127, description: 'Insect with giant pincers', gender: 'Male & Female', category: 'Stag Beetle' },
  { name: 'Tauros', number: 128, description: 'Bull creature with three tails', gender: 'Male', category: 'Wild Bull' },
  { name: 'Magikarp', number: 129, description: 'Weak fish jumping helplessly', gender: 'Male & Female', category: 'Fish' },
  { name: 'Gyarados', number: 130, description: 'Massive water dragon with fury', gender: 'Male & Female', category: 'Atrocious' },
  { name: 'Lapras', number: 131, description: 'Gentle sea turtle with shell back', gender: 'Male & Female', category: 'Transport' },
  { name: 'Ditto', number: 132, description: 'Blob transforming into any form', gender: "Unknown", category: 'Transform' },
  { name: 'Eevee', number: 133, description: 'Fluffy mammal with multiple evolutions', gender: 'Male & Female', category: 'Evolution' },
  { name: 'Vaporeon', number: 134, description: 'Blue aquatic evolution form', gender: 'Male & Female', category: 'Bubble Jet' },
  { name: 'Jolteon', number: 135, description: 'Yellow spiky electric evolution', gender: 'Male & Female', category: 'Lightning' },
  { name: 'Flareon', number: 136, description: 'Red fluffy fire evolution form', gender: 'Male & Female', category: 'Flame' },
  { name: 'Porygon', number: 137, description: 'Digital creature made of polygons', gender: "Unknown", category: 'Virtual' },
  { name: 'Omanyte', number: 138, description: 'Prehistoric spiral shell creature', gender: 'Male & Female', category: 'Spiral' },
  { name: 'Omastar', number: 139, description: 'Ancient cephalopod with tentacles', gender: 'Male & Female', category: 'Spiral' },
  { name: 'Kabuto', number: 140, description: 'Prehistoric armored creature', gender: 'Male & Female', category: 'Shellfish' },
  { name: 'Kabutops', number: 141, description: 'Evolution with enhanced combat abilities', gender: 'Male & Female', category: 'Shellfish' },
  { name: 'Aerodactyl', number: 142, description: 'Pterodactyl fossil creature flying', gender: 'Male & Female', category: 'Fossil' },
  { name: 'Snorlax', number: 143, description: 'Giant sleeping creature blocking paths', gender: 'Male & Female', category: 'Sleeping' },
  { name: 'Articuno', number: 144, description: 'Legendary ice bird of winter', gender: "Unknown", category: 'Freeze' },
  { name: 'Zapdos', number: 145, description: 'Legendary electric storm bird', gender: "Unknown", category: 'Electric' },
  { name: 'Moltres', number: 146, description: 'Legendary fire phoenix bird', gender: "Unknown", category: 'Flame' },
  { name: 'Dratini', number: 147, description: 'Dragon serpent growing into power', gender: 'Male & Female', category: 'Dragon' },
  { name: 'Dragonair', number: 148, description: 'Blue dragon with pearl and abilities', gender: 'Male & Female', category: 'Dragon' },
  { name: 'Dragonite', number: 149, description: 'Powerful dragon with wings', gender: 'Male & Female', category: 'Dragon' },
  { name: 'Mewtwo', number: 150, description: 'Genetically engineered psychic clone', gender: "Unknown", category: 'Genetic' },
  { name: 'Mew', number: 151, description: 'Mythical ancestor of all Pokémon', gender: "Unknown", category: 'New Species' }
];

export default firstGenPokemonList;