const firstGenPokemonList = [
  { name: 'Bulbasaur', number: 1, description: 'Grass-type with a bulb on its back' },
  { name: 'Ivysaur', number: 2, description: 'Grass/poison-type with a pink flower budding' },
  { name: 'Venusaur', number: 3, description: 'Large toad-like creature with fully bloomed flower' },
  { name: 'Charmander', number: 4, description: 'Fire-type lizard with flame on tail' },
  { name: 'Charmeleon', number: 5, description: 'Red dragon-like creature with horns' },
  { name: 'Charizard', number: 6, description: 'Orange dragon with blue wings' },
  { name: 'Squirtle', number: 7, description: 'Blue turtle with brown shell' },
  { name: 'Wartortle', number: 8, description: 'Blue creature with fuzzy ears' },
  { name: 'Blastoise', number: 9, description: 'Armored water turtle with cannons' },
  { name: 'Caterpie', number: 10, description: 'Green caterpillar with yellow antenna' },
  { name: 'Metapod', number: 11, description: 'Cocoon-like creature with hardened exterior' },
  { name: 'Butterfree', number: 12, description: 'Purple butterfly with large wings' },
  { name: 'Weedle', number: 13, description: 'Venomous caterpillar with spikes' },
  { name: 'Kakuna', number: 14, description: 'Yellow cocoon in hardened shell' },
  { name: 'Beedrill', number: 15, description: 'Large wasp with sharp stingers' },
  { name: 'Pidgey', number: 16, description: 'Small brown bird with red feet' },
  { name: 'Pidgeotto', number: 17, description: 'Larger pigeon with skilled flight' },
  { name: 'Pidgeot', number: 18, description: 'Powerful flying bird with massive wings' },
  { name: 'Rattata', number: 19, description: 'Purple mouse with sharp teeth' },
  { name: 'Raticate', number: 20, description: 'Larger rodent with buck teeth' },
  { name: 'Spearow', number: 21, description: 'Small orange bird with pointed beak' },
  { name: 'Fearow', number: 22, description: 'Large brown bird with long neck' },
  { name: 'Ekans', number: 23, description: 'Purple snake that expands when threatened' },
  { name: 'Arbok', number: 24, description: 'Massive cobra with intimidating hood' },
  { name: 'Pikachu', number: 25, description: 'Yellow mouse with red cheeks emitting electricity' },
  { name: 'Raichu', number: 26, description: 'Larger yellow rodent with orange striped tail' },
  { name: 'Sandshrew', number: 27, description: 'Yellow armadillo that digs underground' },
  { name: 'Sandslash', number: 28, description: 'Spiky sand creature with sharp claws' },
  { name: 'Nidoran♀', number: 29, description: 'Small purple female with poisonous spikes' },
  { name: 'Nidorina', number: 30, description: 'Purple creature with horn and venom' },
  { name: 'Nidoqueen', number: 31, description: 'Powerful female with poisonous spikes' },
  { name: 'Nidoran♂', number: 32, description: 'Small purple male with sharp horn' },
  { name: 'Nidorino', number: 33, description: 'Purple male with developing horn' },
  { name: 'Nidoking', number: 34, description: 'Powerful male with large horn' },
  { name: 'Clefairy', number: 35, description: 'Pink fairy-like creature with pointed ears' },
  { name: 'Clefable', number: 36, description: 'Large pink creature with fairy wings' },
  { name: 'Vulpix', number: 37, description: 'Orange fox with six tails' },
  { name: 'Ninetales', number: 38, description: 'Elegant fox with nine beautiful tails' },
  { name: 'Jigglypuff', number: 39, description: 'Pink round creature whose song puts foes asleep' },
  { name: 'Wigglytuff', number: 40, description: 'Large pink fluffy creature with pointed ears' },
  { name: 'Zubat', number: 41, description: 'Purple bat hanging upside down in caves' },
  { name: 'Golbat', number: 42, description: 'Larger purple bat with sharp fangs' },
  { name: 'Oddish', number: 43, description: 'Blue creature with grass leaves on head' },
  { name: 'Gloom', number: 44, description: 'Blue plant creature with pink flower' },
  { name: 'Vileplume', number: 45, description: 'Large red flower with leafy base' },
  { name: 'Paras', number: 46, description: 'Orange crab with mushrooms on back' },
  { name: 'Parasect', number: 47, description: 'Large crab dominated by giant mushroom' },
  { name: 'Venonat', number: 48, description: 'Bug creature with large insect-like eyes' },
  { name: 'Venomoth', number: 49, description: 'Purple moth with toxic spores' },
  { name: 'Diglett', number: 50, description: 'Ground creature peeking above soil' },
  { name: 'Dugtrio', number: 51, description: 'Three Diglett heads connected underground' },
  { name: 'Meowth', number: 52, description: 'Gray cat with gold coin on forehead' },
  { name: 'Persian', number: 53, description: 'Elegant cat with sleek fur' },
  { name: 'Psyduck', number: 54, description: 'Yellow duck with psychic powers' },
  { name: 'Golduck', number: 55, description: 'Blue duck with psychic abilities' },
  { name: 'Mankey', number: 56, description: 'Pig-like creature prone to tantrums' },
  { name: 'Primeape', number: 57, description: 'Powerful ape constantly enraged' },
  { name: 'Growlithe', number: 58, description: 'Orange dog loyal with fire-breathing' },
  { name: 'Arcanine', number: 59, description: 'Majestic tiger-like beast with fiery mane' },
  { name: 'Poliwag', number: 60, description: 'Blue tadpole with swirl pattern on belly' },
  { name: 'Poliwhirl', number: 61, description: 'Amphibian with spiral pattern' },
  { name: 'Poliwrath', number: 62, description: 'Powerful humanoid with martial arts' },
  { name: 'Abra', number: 63, description: 'Psychic creature that teleports instantly' },
  { name: 'Kadabra', number: 64, description: 'Powerful psychic with spoon-bending' },
  { name: 'Alakazam', number: 65, description: 'Ultra-intelligent psychic with IQ of 5000' },
  { name: 'Machop', number: 66, description: 'Fighting creature with powerful muscles' },
  { name: 'Machoke', number: 67, description: 'Muscular fighter with enhanced strength' },
  { name: 'Machamp', number: 68, description: 'Four-armed powerhouse with fighting prowess' },
  { name: 'Bellsprout', number: 69, description: 'Plant creature resembling bell' },
  { name: 'Weepinbell', number: 70, description: 'Carnivorous plant that snaps at prey' },
  { name: 'Victreebel', number: 71, description: 'Venus flytrap-like creature with acid' },
  { name: 'Tentacool', number: 72, description: 'Jellyfish with blue body and tentacles' },
  { name: 'Tentacruel', number: 73, description: 'Giant jellyfish with eighty tentacles' },
  { name: 'Geodude', number: 74, description: 'Rock creature with floating boulders' },
  { name: 'Graveler', number: 75, description: 'Larger rocky creature with rolling form' },
  { name: 'Golem', number: 76, description: 'Massive rock creature with powerful shell' },
  { name: 'Ponyta', number: 77, description: 'Yellow horse with flaming mane' },
  { name: 'Rapidash', number: 78, description: 'Horse with fiery horn and speed' },
  { name: 'Slowpoke', number: 79, description: 'Pink psychic creature with slow movement' },
  { name: 'Slowbro', number: 80, description: 'Pink creature with shell on tail' },
  { name: 'Magnemite', number: 81, description: 'Electric steel creature with magnetism' },
  { name: 'Magneton', number: 82, description: 'Three Magnemite linked together' },
  { name: "Farfetch'd", number: 83, description: 'Duck carrying green onion stick' },
  { name: 'Doduo', number: 84, description: 'Two-headed bird running at speed' },
  { name: 'Dodrio', number: 85, description: 'Three-headed bird with coordination' },
  { name: 'Seel', number: 86, description: 'White seal swimming in frozen waters' },
  { name: 'Dewgong', number: 87, description: 'Sea lion with ice armor' },
  { name: 'Grimer', number: 88, description: 'Purple sludge creature with fumes' },
  { name: 'Muk', number: 89, description: 'Massive sludge pile corroding everything' },
  { name: 'Shellder', number: 90, description: 'Purple clam defending with shell' },
  { name: 'Cloyster', number: 91, description: 'Shellfish with impenetrable spikes' },
  { name: 'Gastly', number: 92, description: 'Purple gas ghost hiding in shadows' },
  { name: 'Haunter', number: 93, description: 'Ghost lowering temperatures around it' },
  { name: 'Gengar', number: 94, description: 'Shadow ghost hiding in walls' },
  { name: 'Onix', number: 95, description: 'Rock serpent made of connected boulders' },
  { name: 'Drowzee', number: 96, description: 'Tapir-like creature feeding on dreams' },
  { name: 'Hypno', number: 97, description: 'Hypnotic creature with pendulum' },
  { name: 'Krabby', number: 98, description: 'Red crab with powerful claws' },
  { name: 'Kingler', number: 99, description: 'Giant crab with massive claw strength' },
  { name: 'Voltorb', number: 100, description: 'Electric sphere resembling pokéball' },
  { name: 'Electrode', number: 101, description: 'Electric ball rolling at incredible speeds' },
  { name: 'Exeggcute', number: 102, description: 'Six plant creatures in coconut shells' },
  { name: 'Exeggutor', number: 103, description: 'Triple-headed palm tree with psychic powers' },
  { name: 'Cubone', number: 104, description: 'Ground creature wearing bone helmet' },
  { name: 'Marowak', number: 105, description: 'Bone-wielding creature skilled in combat' },
  { name: 'Hitmonlee', number: 106, description: 'Fighting master with spring-like legs' },
  { name: 'Hitmonchan', number: 107, description: 'Boxer with incredible punch velocity' },
  { name: 'Lickitung', number: 108, description: 'Pink creature with extremely long tongue' },
  { name: 'Koffing', number: 109, description: 'Purple gas ball producing toxic fumes' },
  { name: 'Weezing', number: 110, description: 'Dual poison gas spheres connected' },
  { name: 'Rhyhorn', number: 111, description: 'Gray rhino-like creature with spiked armor' },
  { name: 'Rhydon', number: 112, description: 'Armored behemoth with drill-like horn' },
  { name: 'Chansey', number: 113, description: 'Pink nurse-like creature that heals' },
  { name: 'Tangela', number: 114, description: 'Vine-covered creature moving with tentacles' },
  { name: 'Kangaskhan', number: 115, description: 'Mother creature with pouch for joey' },
  { name: 'Horsea', number: 116, description: 'Small seahorse shooting water spirals' },
  { name: 'Seadra', number: 117, description: 'Sea dragon with spiky fins' },
  { name: 'Goldeen', number: 118, description: 'Red and white goldfish with crown' },
  { name: 'Seaking', number: 119, description: 'Noble fish with sharp horn' },
  { name: 'Staryu', number: 120, description: 'Starfish with glowing red core' },
  { name: 'Starmie', number: 121, description: 'Crystalline starfish with geometric perfection' },
  { name: 'Mr. Mime', number: 122, description: 'Psychic mime creating invisible barriers' },
  { name: 'Scyther', number: 123, description: 'Bug creature with sharp scythe claws' },
  { name: 'Jynx', number: 124, description: 'Ice-psychic humanoid with kiss attacks' },
  { name: 'Electabuzz', number: 125, description: 'Electric creature with tiger stripes' },
  { name: 'Magmar', number: 126, description: 'Fire creature igniting surroundings' },
  { name: 'Pinsir', number: 127, description: 'Insect with giant pincers' },
  { name: 'Tauros', number: 128, description: 'Bull creature with three tails' },
  { name: 'Magikarp', number: 129, description: 'Weak fish jumping helplessly' },
  { name: 'Gyarados', number: 130, description: 'Massive water dragon with fury' },
  { name: 'Lapras', number: 131, description: 'Gentle sea turtle with shell back' },
  { name: 'Ditto', number: 132, description: 'Blob transforming into any form' },
  { name: 'Eevee', number: 133, description: 'Fluffy mammal with multiple evolutions' },
  { name: 'Vaporeon', number: 134, description: 'Blue aquatic evolution form' },
  { name: 'Jolteon', number: 135, description: 'Yellow spiky electric evolution' },
  { name: 'Flareon', number: 136, description: 'Red fluffy fire evolution form' },
  { name: 'Porygon', number: 137, description: 'Digital creature made of polygons' },
  { name: 'Omanyte', number: 138, description: 'Prehistoric spiral shell creature' },
  { name: 'Omastar', number: 139, description: 'Ancient cephalopod with tentacles' },
  { name: 'Kabuto', number: 140, description: 'Prehistoric armored creature' },
  { name: 'Kabutops', number: 141, description: 'Evolution with enhanced combat abilities' },
  { name: 'Aerodactyl', number: 142, description: 'Pterodactyl fossil creature flying' },
  { name: 'Snorlax', number: 143, description: 'Giant sleeping creature blocking paths' },
  { name: 'Articuno', number: 144, description: 'Legendary ice bird of winter' },
  { name: 'Zapdos', number: 145, description: 'Legendary electric storm bird' },
  { name: 'Moltres', number: 146, description: 'Legendary fire phoenix bird' },
  { name: 'Dratini', number: 147, description: 'Dragon serpent growing into power' },
  { name: 'Dragonair', number: 148, description: 'Blue dragon with pearl and abilities' },
  { name: 'Dragonite', number: 149, description: 'Powerful dragon with wings' },
  { name: 'Mewtwo', number: 150, description: 'Genetically engineered psychic clone' },
  { name: 'Mew', number: 151, description: 'Mythical ancestor of all Pokémon' }
];

export default firstGenPokemonList;